# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"

localrules: all

include: "rules/common.smk"

include: "rules/01_mapping.smk"
include: "rules/02_variant_calling.smk"
include: "rules/03_create_regions_fastas.smk"


rule all:
    input:
        "results/variants/filtered/all.vcf",
        "results/variants/filtered/biallelic-snps.vcf",
        get_region_fasta_filenames,
        get_region_reference_fasta_filenames
        
