# List of samples in FASTQ format
samples: "config/samples.csv"


# Read group settings, no need to change this
read_group:
  platform: "ILLUMINA"
  library: "1"

  
# Reference genome
ref:
  name: "TAIR-10"
  genome: "/ebio/abt6_projects8/ath_somaclonal_variation/data/reference_genomes/Col-0/TAIR10/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa"


# Trimming parameters
read_trimming:
  adapter: "CTGTCTCTTATA" # NEXTERA

  
# Parental Variant calling parameters, no need to change this normally
variant_calling:
  threads: 10
  java_options: "-Xmx24g -Xms24g"


# Hard variant filtering parameters
# The filtering is performed individually for SNPs and Indels.
#
# The filter is not strict, and should be adapted as needed
variant_filtering:
  snps_filter: "QD < 5.0 || FS > 60.0 || MQ < 50.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
  indels_filter: "QD < 5.0 || FS > 200.0 || ReadPosRankSum < -20.0"
