# List of samples in FASTQ format
samples: "config/samples.csv"


# Read group settings, no need to change this
read_group:
  platform: "ILLUMINA"
  library: "1"

  
# Reference genome
ref:
  name: "EMOY2_2"
  genome: "/ebio/abt6_projects9/pathodopsis_HpA_Effectors/data/references/HyaAraEmoy2_2.fa"
  #genome: "/ebio/abt6_projects8/ath_somaclonal_variation/data/reference_genomes/Col-0/TAIR10/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa"


# Trimming parameters
read_trimming:
  adapter: "CTGTCTCTTATA" # NEXTERA

  
# Parental Variant calling parameters, no need to change this normally
variant_calling:
  threads: 10
  java_options: "-Xmx24g -Xms24g"
  extra: ""
# Important: if you use PCR free libraries, adjust the following option
# in the above variant_calling settings as follows:
# extra: "--pcr-indel-model NONE"


# Hard variant filtering parameters
# The filtering is performed individually for SNPs and Indels.
#
# The filter is not strict, and should be adapted as needed
variant_filtering:
  snps_filter: "QD < 5.0 || FS > 60.0 || MQ < 50.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0 || SOR > 4.0"
  indels_filter: "QD < 5.0 || FS > 200.0 || ReadPosRankSum < -20.0 || SOR > 10.0"


# Additional parameters for biallelic SNP VCF
biallelic_snps:
  filter: ""
  allowed_missing_fraction: 0.1


# # Create fasta files for specific regions for each sample (e.g. effectors)
regions:
  - name: "ATR13"
    position: "scaffold_289:14483-15264"
